- name: UTIP Trader - Prepare release
  hosts: all
  vars:
    srcDir: "/home/ansible-ftp/releases/uaTrader"
    fileName: "uaTrader.txt"
  tasks:
    - name: Run
      ansible.builtin.shell: |
        directoryNsis="/home/ansible-ftp/releases/uaTrader/nsis"
        directoryBuilds="/home/ansible-ftp/releases/uaTrader/builds"
        if [ ! -d "$directoryNsis" ]; then
          echo "Папка $directoryNsis не существует."
          exit 1
        fi
      register: lalala

    - name: "Debug: lalala"
      debug: var=lalala
