- name: UTIP Trader - Prepare release
  hosts: all
  vars:
    srcDir: "/home/ansible-ftp/releases/uaTrader"
    fileName: "uaTrader.txt"
  tasks:
    - name: Run
      ansible.builtin.shell: |
#        !/bin/bash

#         Указываем путь к папке
        directoryNsis="/home/ansible-ftp/releases/uaTrader/nsis"
        directoryBuilds="/home/ansible-ftp/releases/uaTrader/builds"

#         Проверяем, существует ли указанная папка
        if [ ! -d "$directoryNsis" ]; then
          echo "Папка $directoryNsis не существует."
          exit 1
        fi

#         Проходим по всем файлам в директории
        for file in "$directoryNsis"/*; do
#           Проверяем, является ли это файлом
          if [ -f "$file" ]; then
#             Извлекаем имя файла без пути
            filename=$(basename "$file")

#             Выделяем подстроку между "_", и "."
            if [[ $filename =~ _([^\.]+) ]] ; then
              substring="${BASH_REMATCH[1]}"

#               Создаем директорию с вычлененным именем
              mkdir -p "$directoryBuilds/$substring"
              echo "Создана директория: $substring"
            fi
          fi
        done
#        search_dir={{ srcDir }}/nsis
#        for entry in "$search_dir"/*
#        do
#        echo ("$entry" | grep -oP "trader_([^.]*).nsis")$1
#        done
      register: lalala

    - name: "Debug: lalala"
      debug: var=lalala
