- name: UTIP Trader - Prepare release
  hosts: all
  vars:
    srcDir: "/home/ansible-ftp/releases/uaTrader"
    fileName: "uaTrader.txt"
  tasks:
    - name: Chmod for prepare.sh
      file:
        path: "{{ srcDir }}/scripts/prepare.sh"
        mode: "a+x"
    - name: Run script
      ansible.builtin.shell: "{{ srcDir }}/scripts/prepare.sh"
      register: lalala

    - name: "Debug: Return information"
      debug: var=lalala
