- name: UTIP Trader - Prepare release
  hosts: all
  vars:
    srcDir: "/home/ansible-ftp/releases/uaTrader"
    fileName: "uaTrader.txt"
  tasks:
    - name: Run
      ansible.builtin.shell: |
        directoryNsis="/home/ansible-ftp/releases/uaTrader/nsis"
        directoryBuilds="/home/ansible-ftp/releases/uaTrader/builds"
        if [ ! -d "$directoryNsis" ]; then
          echo "Папка $directoryNsis не существует."
          exit 1
        fi
        for file in "$directoryNsis"/*; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            if [[ $filename =~ _([^\.]+) ]] ; then
              substring="${BASH_REMATCH[1]}"
              mkdir -p "$directoryBuilds/$substring"
              echo "Создана директория: $substring"
            fi
          fi
        done
      register: lalala

    - name: "Debug: lalala"
      debug: var=lalala
