- name: UTIP Trader - Prepare release
  hosts: all
#  vars:
#    destinationDir: "%TEMP%\\ansible"
#    srcDir: "/releases/uaTrader/build/"
#    fileName: "trader.txt"
  tasks:
    - name: Hahaha
      debug:
        msg: "Hello World! Ebaaa"
