- name: UTIP Trader - Prepare release
  hosts: all
  vars:
    srcDir: "/home/ansible-ftp/releases/uaTrader"
    fileName: "uaTrader.txt"
  tasks:
    - name: Run
      ansible.builtin.shell: |
        search_dir={{ srcDir }}/nsis
        for entry in "$search_dir"/*
        do
        echo "$entry" | grep -oP "trader_([^.]*).nsis"
        done
      register: lalala

    - name: "Debug: lalala"
      debug: var=lalala
