- name: UTIP Trader - Updater
  hosts: all
  vars:
    destinationDir: "C:\\Program Files\\Ansible\\releases\\uaTrader"
    srcDir: "releases/uaTrader/builds"
    fileName: "uaTrader.txt"
  tasks:
    - name: Create temporary directory
      ansible.windows.win_file:
        path: "{{ destinationDir }}"
        state: directory

    - name: Uploading UTIP Trader
      ansible.windows.win_get_url:
        dest: "{{ destinationDir }}\\{{ fileName }}"
        url: "ftp://{{ ftpHost }}/{{ srcDir }}/{{ brandName }}/{{ fileName }}"
        url_username: "{{ ftpUser }}"
        url_password: "{{ ftpPass }}"
        force: true
