- name: UTIP Admin - Updater
  hosts: all
  serial: 5
  vars:
    tempDirectoryPathName: "C:\\Program Files\\Ansible\\releases\\uaWebOffice"
    utipAdminArchiveName: "uaWebOffice.zip"
    woReleasePartPath: "releases/uaWebOffice/uaWebOffice.zip"
  tasks:
    - name: Create temporary directory
      ansible.windows.win_file:
        path: "{{ tempDirectoryPathName }}"
        state: directory

    - name: "Debug: tempDirectoryPathName"
      debug: var=tempDirectoryPathName

    - name: Uploading archive of UTIP Admin application
      ansible.windows.win_get_url:
        dest: "{{ tempDirectoryPathName }}\\{{ utipAdminArchiveName }}"
        url: "ftp://{{ ftpHost }}/{{ woReleasePartPath }}"
        url_username: "{{ ftpUser }}"
        url_password: "{{ ftpPass }}"
        force: true

    - name: Create temporary directory
      ansible.windows.win_file:
        path: "{{ tempDirectoryPathName }}\\source"
        state: directory

    - name: Unzip UTIP Admin Release
      community.windows.win_unzip:
        src: "{{ tempDirectoryPathName }}\\{{ utipAdminArchiveName }}"
        dest: "{{ tempDirectoryPathName }}\\source"
        recursive: true
