- name: UTIP Admin - Updater
  hosts: all
  vars:
    tempDirectoryPathName: "%TEMP%\\ansible"
    utipAdminArchiveName: "uaWebOffice.zip"
    woReleasePartPath: "releases/uaWebOffice/uaWebOffice.zip"
  tasks:
    - name: Create temporary directory
      ansible.windows.win_file:
        path: "{{ tempDirectoryPathName }}"
        state: directory

    - name: "Debug: tempDirectoryPathName"
      debug: var=tempDirectoryPathName

    - name: Uploading archive of UTIP Admin application
      ansible.windows.win_get_url:
        dest: "{{ tempDirectoryPathName }}\\{{ utipAdminArchiveName }}"
        url: "ftp://{{ ftpHost }}/{{ woReleasePartPath }}"
        url_username: "{{ ftpUser }}"
        url_password: "{{ ftpPass }}"
        force: true

    - name: "lallala"
      community.windows.win_unzip:
        src: "{{ tempDirectoryPathName }}\\{{ utipAdminArchiveName }}"
        dest: "{{ tempDirectoryPathName }}"
        recurse: true
