- name: UTIP Admin - Updater
  hosts: all
  vars:
    tempDirectoryPathName: "%TEMP%\\ansible\\uaWebOffice"
    utipAdminArchiveName: "uaWebOffice.zip"
    woReleasePartPath: "/home/ansible-ftp/releases/uaWebOffice/uaWebOffice.zip"
  tasks:
    - name: Create temporary directory
      ansible.windows.win_file:
        path: "{{ tempDirectoryPathName }}"
        state: directory

    - name: "Debug: tempDirectoryPathName"
      debug: var=tempDirectoryPathName

    - name: Uploading archive of UTIP Admin application
      ansible.windows.win_copy:
        dest: "{{ tempDirectoryPathName }}\\{{ utipAdminArchiveName }}"
        src: "{{ woReleasePartPath }}"
        force: true
