- name: UTIP Admin - Updater
  hosts: all
  vars:
    destDirPath: "%TEMP%\\ansible\\uaWebOffice"
    destFilePath: "%TEMP%\\ansible\\uaWebOffice\\uaWebOffice.zip"
    sourceFilePath: "/root/snap/semaphore/commonuaWebOffice.zip"
  tasks:
    - name: Create temporary directory
      ansible.windows.win_file:
        path: "{{ destDirPath }}"
        state: directory

    - name: "Debug: tempDirectoryPathName"
      debug: var=tempDirectoryPathName

    - name: Uploading archive of UTIP Admin application
      become: yes
      ansible.windows.win_copy:
        dest: "{{ destFilePath }}"
        src: "{{ sourceFilePath }}"
        force: true
