- name: UTIP Admin - Updater
  hosts: all
  vars:
    utipAdminArchiveName: "uaWebOffice.zip"
  tasks:
    - name: Create temporary directory
      ansible.windows.win_tempfile:
        state: directory
        suffix: files
      register: tempDirectoryPathName

    - name: "Debug: tempDirectoryPathName"
      debug: var=tempDirectoryPathName.path

    - name: Uploading archive of UTIP Admin application
      ansible.windows.win_copy:
        dest: "{{ tempDirectoryPathName.path }}/{{ utipAdminArchiveName }}"
        src: "/home/releases/uaWebOffice/{{ utipAdminArchiveName }}"